using FluentAssertions;
using Microsoft.Testing.Platform.Configurations;

namespace GameOfLife.Engine.Tests;

public class EngineTests
{
    private string _testDirectory = TestContext.CurrentContext.TestDirectory;
    private Configuration _configuration;
    private IBoard _board;
    private INeighbourLocationCalculator _neighbourLocationCalculator;
    private IGame _game;

    [SetUp]
    public void Setup()
    {
        _configuration = new Configuration(20, 20);
        _board = new Board(_configuration);
        _neighbourLocationCalculator = new NeighbourLocationCalculator(_configuration);
        _game = new Game(_board, _neighbourLocationCalculator);
    }

    [Test]
    public void Test1_OneAliveCell()
    {
        // Arrange
        var expectedBoard = @"....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
";
        var filePath = GetFilePath(nameof(Test1_OneAliveCell));


        // Act
        _game.InitializeGame(filePath);

        _game.Iterate();

        // Assert
        var actualBoard = _board.ToString();

        actualBoard.Should().Be(expectedBoard);
    }

    [Test]
    public void Test1_TwoAliveNeighbours()
    {
        // Arrange
        var expectedBoard = @"....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
";
        var filePath = GetFilePath(nameof(Test1_TwoAliveNeighbours));

        // Act
        _game.InitializeGame(filePath);

        _game.Iterate();

        // Assert
        var actualBoard = _board.ToString();

        actualBoard.Should().Be(expectedBoard);
    }

    [Test]
    public void Test1_LTromine()
    {
        // Arrange
        var expectedBoard = @"....................
....................
....................
.....OO.............
.....OO.............
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
";
        var filePath = GetFilePath(nameof(Test1_LTromine));

        // Act
        _game.InitializeGame(filePath);

        _game.Iterate();

        // Assert
        var actualBoard = _board.ToString();

        actualBoard.Should().Be(expectedBoard);
    }

    [Test]
    public void Test1_Cross()
    {
        // Arrange
        var expectedBoard = @"....................
....................
....................
....OOO.............
....O.O.............
....OOO.............
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
";
        var filePath = GetFilePath(nameof(this.Test1_Cross));


        // Act
        _game.InitializeGame(filePath);

        _game.Iterate();

        // Assert
        var actualBoard = _board.ToString();

        actualBoard.Should().Be(expectedBoard);
    }

    [Test]
    public void Test2_Stability()
    {
        // Arrange
        var expectedBoard = @"....................
....................
....................
....................
....OO..............
....OO..............
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
";
        var filePath = GetFilePath(nameof(Test2_Stability));

        // Act
        _game.InitializeGame(filePath);

        // 1 step
        _game.Iterate();
        var actualBoardStep1 = _board.ToString();

        actualBoardStep1.Should().Be(expectedBoard);

        // 2 step
        _game.Iterate();
        var actualBoardStep2 = _board.ToString();

        actualBoardStep2.Should().Be(expectedBoard);

        // 3 step
        _game.Iterate();
        var actualBoardStep3 = _board.ToString();

        actualBoardStep3.Should().Be(expectedBoard);

        // 4 step
        _game.Iterate();
        var actualBoardStep4 = _board.ToString();

        actualBoardStep4.Should().Be(expectedBoard);

        // 5 step
        _game.Iterate();
        var actualBoardStep5 = _board.ToString();

        actualBoardStep5.Should().Be(expectedBoard);
    }


    private string GetFilePath(string fileName)
    {
        var filePath = Path.Combine(_testDirectory, fileName + ".txt");
        Assert.That(File.Exists(filePath), Is.True, "Файл не найден в директории сборки.");

        return filePath;
    }
}
